// Code generated by "stringer -type Role -linecomment"; DO NOT EDIT.

package opds2

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Author-1]
	_ = x[Translator-2]
	_ = x[Editor-3]
	_ = x[Artist-4]
	_ = x[Illustrator-5]
	_ = x[Letterer-6]
	_ = x[Penciler-7]
	_ = x[Colorist-8]
	_ = x[Inker-9]
	_ = x[Narrator-10]
	_ = x[Publisher-11]
	_ = x[Imprint-12]
}

const _Role_name = "authortranslatoreditorartistillustratorlettererpencilercoloristinkernarratorpublisherimprint"

var _Role_index = [...]uint8{0, 6, 16, 22, 28, 39, 47, 55, 63, 68, 76, 85, 92}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
